apiVersion: batch/v1
kind: Job
metadata:
  name: phptravel
spec:
  template:
    spec:
      containers:
      - name: phptravel
        image: deepshikharai/phptravel
        imagePullPolicy: Always
        volumeMounts:
                #name must match the volume name below
           - name: nfs
             mountPath: "/data"
      restartPolicy: Never
      volumes:
      - name: nfs
        persistentVolumeClaim:
         claimName: nfs
  backoffLimit: 4
